name: CI

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo check --all

  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo test --all

  lints:
    name: Lints
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain: [stable]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all -- -D warnings